version: '3'
services:
  nodeapp:
    build: .
    networks:
      - monitoring
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus:v2.13.1
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:6.4.3
    networks:
      - monitoring
    ports:
      - "3000:3000"

networks:
  monitoring:
